# Generated by Django 5.2 on 2026-02-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='stock_deduit',
            field=models.BooleanField(default=False),
        ),
    ]
